### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by kruug** [ForJ-Latech/fwm#10]
Looking to add more technology to my D&D sessions.  I would love to see why I should download and use this tool.  Please add visuals and screenshots to show me what it looks like and how to use it.

**Comment by WingardiumMateosa** [comment]
https://github.com/ForJ-Latech/fwm/tree/master/z-class-documentation/packaged_documentation should textually cover what you need

**Comment by james-ehlmann** [comment]
You had a great point kruug. I went ahead and made some screen shots of the software in action. 

https://imgur.com/gallery/OEmn7aD
